import type { NextPage } from "next"
import { useSession, signOut } from "next-auth/react"
import Head from "next/head"
import { CartSlice } from "../../store/createCartSlice"
import { useStore } from "../../store/useStore"
import { trpc } from "../utils/trpc"

const Home: NextPage = () => {
  trpc.useQuery(["getProducts"])
  const products = trpc.useQuery(["productsList"])
  const { data: session, status } = useSession()
  const { state, cart } = useStore() as CartSlice
  // const exampleData = trpc.useQuery(["example"]);
  // const { invalidateQueries } = trpc.useContext()
  // const createExample = trpc.useMutation("create-example", {
  //   onSuccess: () => invalidateQueries("example"),
  // })

  return (
    <>
      <Head>
        <title>Create t3 App</title>
        <meta name="description" content="Generated by create t3 app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col items-center justify-center w-1/2 min-h-screen mx-auto">
        <h1 className="font-extrabold text-center text-7xl">
          Create <span className="text-blue-500">t3</span> App
        </h1>

        <div className="w-full">
          <div className="py-6 text-xl">
            {products.data ? (
              <p>{JSON.stringify(products.data)}</p>
            ) : (
              <p>Loading...</p>
            )}
          </div>
          <div className="py-6 text-2xl">
            <button onClick={() => signOut()}>Logout</button>

            {/* {exampleData.data ? (
              <div>
                {exampleData.data.length === 0 ? (
                  <p className="text-2xl">No data available, create new!</p>
                ) : (
                  exampleData.data.map(({ id }) => <p key={id}>{id}</p>)
                )}
              </div>
            ) : (
              <p>Loading...</p>
            )} */}
          </div>
          {/* <button
            onClick={() => createExample.mutate()}
            className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
          >
            Create New Example
          </button> */}
        </div>
      </div>
    </>
  )
}

export default Home
